const $=(s)=>document.querySelector(s); const video=$("#video"),layer=$("#danmakuLayer"),status=$("#status");
let videoUrl="",cameraStream=null,danmaku=[];
let requestSequence=0;const nativeRequests=new Map();
function say(text,error=false){status.textContent=text;status.style.color=error?"#ff9baa":""}
function config(){return JSON.parse(localStorage.getItem("neoai-mobile-config-v1")||"{}");}
window.__neoaiResolveNativeRequest=(id,value)=>{const pending=nativeRequests.get(id);if(!pending)return;clearTimeout(pending.timer);nativeRequests.delete(id);try{const envelope=JSON.parse(value);if(!envelope.ok)pending.reject(new Error(envelope.error||`API ${envelope.status||"失败"}`));else pending.resolve(JSON.parse(envelope.body||"{}"))}catch(error){pending.reject(error)}};
async function requestJson(url,{method="GET",apiKey="",body=""}={}){if(window.NeoAIAndroid?.requestJson)return new Promise((resolve,reject)=>{const id=`media-${Date.now()}-${++requestSequence}`;const timer=setTimeout(()=>{nativeRequests.delete(id);reject(new Error("服务连接超时"))},50000);nativeRequests.set(id,{resolve,reject,timer});window.NeoAIAndroid.requestJson(id,url,method,apiKey,body)});const response=await fetch(url,{method,headers:{...(body?{"Content-Type":"application/json"}:{}),...(apiKey?{Authorization:`Bearer ${apiKey}`}:{})},...(body?{body}:{})});if(!response.ok)throw new Error(`API ${response.status}`);return response.json()}
async function ask(prompt){
  if(window.neopet?.ai) return (await window.neopet.ai.chat([{role:"user",content:prompt}])).reply;
  const c=config(),key=sessionStorage.getItem("neoai-api-key")||""; if(!c.baseUrl||!c.model) throw new Error("请先回到 NeoAI 设置填写 API 地址和模型");
  const data=await requestJson(`${c.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",apiKey:key,body:JSON.stringify({model:c.model,temperature:.3,messages:[{role:"system",content:"你是专业视频字幕助手。严格按用户要求输出纯文本，不要Markdown。"},{role:"user",content:prompt}]})}); return data.choices?.[0]?.message?.content||"";
}
function showDanmaku(item){const el=document.createElement("span");el.className="danmaku";el.textContent=item.text;el.style.top=`${8+(item.lane%7)*12}%`;layer.append(el);el.addEventListener("animationend",()=>el.remove())}
video.addEventListener("timeupdate",()=>{for(const item of danmaku){if(!item.played&&video.currentTime>=item.time){item.played=true;showDanmaku(item)}}});
video.addEventListener("seeked",()=>{for(const item of danmaku)item.played=item.time<video.currentTime-1});
$("#videoFile").addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=URL.createObjectURL(file);video.src=videoUrl;say(`已载入 ${file.name}`)});
$("#addDanmaku").addEventListener("click",()=>{const text=$("#danmakuText").value.trim();if(!text)return;danmaku.push({time:video.currentTime,text,lane:danmaku.length%7,played:false});$("#danmakuText").value="";showDanmaku(danmaku.at(-1));say(`已添加 ${danmaku.length} 条弹幕`)});
$("#translate").addEventListener("click",async()=>{const source=$("#sourceText").value.trim();if(!source)return say("请先粘贴字幕或台词",true);say("正在翻译…");try{$("#translatedText").value=await ask(`把以下视频字幕翻译成${$("#targetLanguage").value}。保留所有时间码、序号、换行和说话人，只输出译文：\n${source.slice(0,24000)}`);say("翻译完成")}catch(e){say(e.message,true)}});
$("#generateDanmaku").addEventListener("click",async()=>{const source=$("#sourceText").value.trim();if(!source)return say("请先提供字幕或台词",true);say("正在生成弹幕…");try{const raw=await ask(`根据下面内容生成10条简短、有趣但友善的中文视频弹幕。每行一条，只输出弹幕：\n${source.slice(0,12000)}`);const lines=raw.split(/\r?\n/).map(x=>x.replace(/^[-\d.、\s]+/,"").trim()).filter(Boolean).slice(0,10);const duration=Number.isFinite(video.duration)?video.duration:60;danmaku=lines.map((text,i)=>({time:(duration/(lines.length+1))*(i+1),text,lane:i%7,played:false}));say(`已生成 ${danmaku.length} 条弹幕，播放视频即可看到`)}catch(e){say(e.message,true)}});
$("#downloadVtt").addEventListener("click",()=>{let text=$("#translatedText").value.trim();if(!text)return say("没有可下载的字幕",true);if(!text.startsWith("WEBVTT"))text=`WEBVTT\n\n${text}`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/vtt"}));a.download="neoai-translated.vtt";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
$("#testCamera").addEventListener("click",async()=>{try{cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});$("#camera").srcObject=cameraStream;say("摄像头和麦克风可用")}catch(e){say(`设备授权失败：${e.message}`,true)}});
$("#createCall").addEventListener("click",async()=>{const room=`NeoAI-${crypto.randomUUID().replaceAll("-","").slice(0,18)}`;const url=`https://meet.jit.si/${room}`;$("#meetingLink").value=url;try{if(window.neopet?.external)await window.neopet.external.open(url);else if(window.NeoAIAndroid)window.location.href=url;else window.open(url,"_blank","noopener");say("通话已创建，把链接发给对方即可加入")}catch(e){say(e.message,true)}});
$("#copyLink").addEventListener("click",async()=>{const value=$("#meetingLink").value;if(!value)return say("请先创建通话",true);await navigator.clipboard.writeText(value);say("通话链接已复制")});
window.addEventListener("beforeunload",()=>{cameraStream?.getTracks().forEach(t=>t.stop());if(videoUrl)URL.revokeObjectURL(videoUrl)});
