plugins { id 'com.android.application' }

android {
    namespace 'ai.neopet.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'ai.neopet.mobile'
        minSdk 26
        targetSdk 36
        versionCode 8
        versionName '0.4.1'
    }

    sourceSets {
        main.assets.srcDirs = ['../../mobile']
    }
}
